import { users } from "@/constants/user";
import { MusicType } from "@/types";

export const musicData: MusicType[] = [
  {
    id: "1",
    music: "The Legend of Mother Swan",
    artist: "The HU",
    addedBy: users[0],
    bpm: 120,
    link: "https://open.spotify.com/track/4P4Sr4CGBInMqaJgiocEar?si=4a0ef0420dde4afe",
    qrCode: "qr-code-1",
    rating: 5,
    category: "Easy",
  },
  {
    id: "2",
    music: "Shireg Shireg",
    artist: "The HU",
    addedBy: users[0],
    bpm: 125,
    link: "https://open.spotify.com/track/59pGjnMnCcD7UrGrSfME1r?si=57e37b9241944f41",
    qrCode: "qr-code-2",
    rating: 5,
    category: "Easy",
  },
  {
    id: "3",
    music: "Sunday Glide",
    artist: "Kermesse",
    addedBy: users[0],
    bpm: 130,
    link: "https://open.spotify.com/track/72Qac2FQd9e21XCibSOhfY?si=c745faf104964bb1",
    qrCode: "qr-code-3",
    rating: 4,
    category: "Easy",
  },
  {
    id: "4",
    music: "In The Garden - okuma Remix",
    artist: "Kusht, okuma",
    addedBy: users[0],
    bpm: 128,
    link: "https://open.spotify.com/track/0Wo6xxKFEBqLOA1om7nYEn?si=26a0a1b8177446d5",
    qrCode: "qr-code-4",
    rating: 4,
    category: "Easy",
  },
  {
    id: "5",
    music: "Tranquilizer - Christian Craken Remix",
    artist: "Oliver Huntemann, Christian Craken",
    addedBy: users[0],
    bpm: 132,
    link: "https://open.spotify.com/track/6cWL1DzfiPlYE9Xk9eML4n?si=0c245d4a20814061",
    qrCode: "qr-code-5",
    rating: 5,
    category: "Sprint",
  },
  {
    id: "6",
    music: "Trust Deficit",
    artist: "Skarby, La Giang",
    addedBy: users[0],
    bpm: 135,
    link: "https://open.spotify.com/track/6UTqAkRE9GEKzXlbj3kleH?si=99428105d7c448c1",
    qrCode: "qr-code-6",
    rating: 4,
    category: "Tempo",
  },
  {
    id: "7",
    music: "Banamba - Radio Mix",
    artist: "We Came",
    addedBy: users[0],
    bpm: 140,
    link: "https://open.spotify.com/track/5opwODfMkHhILxQXArka8m?si=e238212ada544a3d",
    qrCode: "qr-code-7",
    rating: 3,
    category: "Sprint",
  },
  {
    id: "8",
    music: "Liquid Green - Original Mix",
    artist: "Township Rebellion",
    addedBy: users[0],
    bpm: 128,
    link: "https://open.spotify.com/track/0BlHlPQWD2aE2ZfZ4aEu49?si=430ef4047e484f0c",
    qrCode: "qr-code-8",
    rating: 5,
    category: "Sprint",
  },
  {
    id: "9",
    music: "Subconscious",
    artist: "Theydream",
    addedBy: users[0],
    bpm: 130,
    link: "https://open.spotify.com/track/5R8PgzKg69PUSLxb2CDgzT?si=99f815c1e7de4c35",
    qrCode: "qr-code-9",
    rating: 4,
    category: "Tempo",
  },
  {
    id: "10",
    music: "Hailstorm - Ann Clue Remix",
    artist: "Theydream, Ann Clue",
    addedBy: users[0],
    bpm: 133,
    link: "https://open.spotify.com/track/4INsV87wHXViqJRAmbOo8t?si=9a7c12382ac641da",
    qrCode: "qr-code-10",
    rating: 5,
    category: "Tempo",
  },
];
