const KEYWORDS = [
  'running playlist',
  'workout music',
  'share playlist',
  'perfect running music',
  'running songs',
  'workout playlist',
  'music for running',
  'running beats',
  'playlist sharing',
  'fitness music',
  'running motivation',
  'workout songs',
  'running rhythm',
  'music sharing',
  'perfect workout playlist',
  'running tempo',
  'fitness playlist',
  'running motivation music',
  'workout beats',
  'playlist collaboration',
  'running music app',
  'workout rhythm',
  'music for workouts',
  'running playlist app',
  'fitness motivation',
  'perfect running beats',
  'workout playlist sharing',
  'running music sharing',
  'fitness music app',
  'running playlist perfect',
];

export default KEYWORDS;
